[project]
name = "Ripplex"
version = "1.0.0"
description = "A Python framework for parallel execution with automatic dependency resolution and variable capture."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "rich>=14.0.0",
]
